%undefine _debugsource_packages
Name:           ollama
Version:        0.12.11
Release:        1
Summary:        Tool for running AI models on-premise
License:        MIT
URL:            https://ollama.com
Source0:        https://github.com/ollama/ollama/archive/refs/tags/v%{version}/%{name}-%{version}.tar.gz
# Generated by running, inside the source tree:
# go mod vendor
# tar cJf ../godeps-for-ollama-0.12.11.tar.xz vendor
Source1:        godeps-for-ollama-%{version}.tar.xz
Source2:        ollama.service
Source3:        %{name}.sysusers
BuildRequires:  cmake
BuildRequires:  ccache
BuildRequires:  git
BuildRequires:  zstd
BuildRequires:  golang
BuildRequires:  compiler(go-compiler)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  systemd-rpm-macros
BuildRequires:  pkgconfig(vulkan)
BuildRequires:  glslc
BuildRequires:  glslang

%description
Ollama is a tool for running AI models on one's own hardware.
It offers a command-line interface and a RESTful API.
New models can be created or existing ones modified in the
Ollama library using the Modelfile syntax.
Source model weights found on Hugging Face and similar sites
can be imported.

%prep
%autosetup -n %{name}-%{version} -a1 -p1

# install dir is off, lib -> lib64
# cmake install location
sed -i -e 's@${CMAKE_INSTALL_PREFIX}/lib/ollama@${CMAKE_INSTALL_PREFIX}/lib64/ollama@' CMakeLists.txt
# overwrite discover/path.go so instead of attempting to discover, LibOllamaPath is set to our path
echo -e 'package discover\nvar LibOllamaPath string = "/usr/lib64/ollama"' > discover/path.go
# for dlopens
sed -i -e 's@"lib/ollama"@"lib64/ollama"@' ml/backend/ggml/ggml/src/ggml.go
 
# install dir for backend *.so's is off usr/bin -> usr/lib64/ollama
sed -i -e 's@${CMAKE_INSTALL_BINDIR}@${OLLAMA_INSTALL_DIR}@' ml/backend/ggml/ggml/src/CMakeLists.txt


%build
#export GOPATH=$(pwd)/vendor:$(pwd)/gopath
#go build
%cmake
%make_build

# out of build
cd ../
go build -v -x

%install
export GOPATH=$(pwd)/vendor:$(pwd)/gopath
install -D -m 0755 %{name} %{buildroot}/%{_bindir}/%{name}
install -D -m 0644 %{SOURCE2} %{buildroot}%{_unitdir}/%{name}.service
install -D -m 0644 %{SOURCE3} %{buildroot}%{_sysusersdir}/%{name}.conf
install -d %{buildroot}%{_localstatedir}/lib/%{name}

mkdir -p "%{buildroot}/%{_docdir}/%{name}"
cp -Ra docs/* "%{buildroot}/%{_docdir}/%{name}"

%make_install -C build
install -d %{buildroot}%{_sysconfdir}/ld.so.conf.d/
cat > %{buildroot}/etc/ld.so.conf.d/ollama.conf <<EOF
%{_libdir}/ollama
EOF

%files
%license LICENSE
%doc %{_docdir}/%{name}
%{_bindir}/%{name}
%{_unitdir}/%{name}.service
%{_sysusersdir}/%{name}.conf
%{_sysconfdir}/ld.so.conf.d/%{name}.conf
%attr(-, ollama, ollama) %{_localstatedir}/lib/%{name}
%{_libdir}/ollama/
